FROM python:3.10-slim

RUN apt-get update && \
    apt-get install -y tini cron rdiff-backup procps tzdata && \
    apt-get clean

ENV TZ=Europe/Madrid
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

ENTRYPOINT ["/usr/bin/tini", "--"]

WORKDIR /app

COPY ../app/requirements.txt .
COPY ../app ./

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8686

CMD ["sh", "-c", "cron && uvicorn main:app --host 0.0.0.0 --port 8686"]