services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    container_name: homelab-backups-container
    ports:
      - "8686:8686"
    volumes:
      - ${BACKUP_SOURCE}:/app/backup_source:ro
      - ${BACKUP_DESTINATION}:/app/backup_destination
      - /etc/localtime:/etc/localtime:ro
      - ${APP_DB_PATH}:/app/db
    environment:
      - TZ=Europe/Paris
      - SERVER_IP=${BACKEND_IP}
    restart: unless-stopped

  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
    container_name: homelab-backups-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_SERVER_IP=${BACKEND_IP}
    depends_on:
      - backend
    restart: unless-stopped