name: Docker Validation

on:
  push:
    paths:
      - "docker/**"
      - "frontend/**"
      - "app/**"
      - ".github/workflows/**"
  pull_request:
    paths:
      - "docker/**"
      - "frontend/**"
      - "app/**"
      - ".github/workflows/**"

jobs:
  hadolint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Hadolint on Backend Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: docker/Dockerfile.backend
          ignore: DL3008,DL3009,DL3015

      - name: Run Hadolint on Frontend Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: docker/Dockerfile.frontend

  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Backend Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile.backend
          push: false
          tags: backend:test

      - name: Build Frontend Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile.frontend
          push: false
          tags: frontend:test
